<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-JPK5SJ4V" ignored="0" name="Test(failed)" tests="40" failures="5" timestamp="11 Mar 2024 13:30:34 GMT" time="0.095" errors="0">
  <testcase name="test1" time="0.0" classname="org.rerunnig.A"/>
  <testcase name="test2" time="0.016" classname="org.rerunnig.A">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.0" classname="org.rerunnig.A">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.0" classname="org.rerunnig.A">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.0" classname="org.rerunnig.A">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.0" classname="org.rerunnig.A">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.001" classname="org.rerunnig.A">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.rerunnig.A.test2(A.java:50)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test3" time="0.0" classname="org.rerunnig.A"/>
  <testcase name="test4" time="0.0" classname="org.rerunnig.A">
    <skipped/>
  </testcase> <!-- test4 -->
  <testcase name="test4" time="0.0" classname="org.rerunnig.A">
    <skipped/>
  </testcase> <!-- test4 -->
  <testcase name="test4" time="0.0" classname="org.rerunnig.A">
    <skipped/>
  </testcase> <!-- test4 -->
  <testcase name="test4" time="0.0" classname="org.rerunnig.A">
    <skipped/>
  </testcase> <!-- test4 -->
  <testcase name="test4" time="0.0" classname="org.rerunnig.A">
    <skipped/>
  </testcase> <!-- test4 -->
  <testcase name="test4" time="0.0" classname="org.rerunnig.A">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.rerunnig.A.test4(A.java:81)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test4 -->
  <testcase name="test5" time="0.0" classname="org.rerunnig.A"/>
  <testcase name="test1" time="0.0" classname="org.rerunnig.C"/>
  <testcase name="test2" time="0.0" classname="org.rerunnig.C"/>
  <testcase name="test3" time="0.0" classname="org.rerunnig.C">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test3" time="0.0" classname="org.rerunnig.C">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test3" time="0.0" classname="org.rerunnig.C">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test3" time="0.0" classname="org.rerunnig.C">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test3" time="0.015" classname="org.rerunnig.C">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test3" time="0.0" classname="org.rerunnig.C">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.rerunnig.C.test3(C.java:63)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase name="test4" time="0.0" classname="org.rerunnig.C"/>
  <testcase name="test5" time="0.0" classname="org.rerunnig.C"/>
  <testcase name="test1" time="0.0" classname="org.rerunnig.B">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.0" classname="org.rerunnig.B">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.0" classname="org.rerunnig.B">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.0" classname="org.rerunnig.B">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.0" classname="org.rerunnig.B">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.0" classname="org.rerunnig.B">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.rerunnig.B.test1(B.java:32)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test2" time="0.0" classname="org.rerunnig.B"/>
  <testcase name="test3" time="0.0" classname="org.rerunnig.B"/>
  <testcase name="test4" time="0.0" classname="org.rerunnig.B"/>
  <testcase name="test5" time="0.0" classname="org.rerunnig.B">
    <skipped/>
  </testcase> <!-- test5 -->
  <testcase name="test5" time="0.0" classname="org.rerunnig.B">
    <skipped/>
  </testcase> <!-- test5 -->
  <testcase name="test5" time="0.0" classname="org.rerunnig.B">
    <skipped/>
  </testcase> <!-- test5 -->
  <testcase name="test5" time="0.0" classname="org.rerunnig.B">
    <skipped/>
  </testcase> <!-- test5 -->
  <testcase name="test5" time="0.0" classname="org.rerunnig.B">
    <skipped/>
  </testcase> <!-- test5 -->
  <testcase name="test5" time="0.0" classname="org.rerunnig.B">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.rerunnig.B.test5(B.java:93)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test5 -->
</testsuite> <!-- Test(failed) -->
